tls:
  certificates:
    - certFile: /etc/letsencrypt/live/surgir.online/fullchain.pem
      keyFile: /etc/letsencrypt/live/surgir.online/privkey.pem
  stores:
    default:
      defaultCertificate:
        certFile: /etc/letsencrypt/live/surgir.online/fullchain.pem
        keyFile: /etc/letsencrypt/live/surgir.online/privkey.pem
